name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: liberica
      - name: execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
