name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 11
          distribution: liberica
      - name: execute build
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build
