name: Dokka publication

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: liberica
      - name: execute build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtmlMultiModule
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
