name: Gradle publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    environment:
      name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: liberica
      - name: execute build
        uses: gradle/gradle-build-action@v2
      - name: Publish
        shell: bash
        run: >
          ./gradlew release --no-daemon --build-cache -Ppublishing.enabled=true
          -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
          -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
